name: Linux build generate_track_list.bin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd_bison_flex
      run: cd ./src/flex/
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
